export enum Message {
  SOMETHING_WENT_WRONG = "SOMETHING_WENT_WRONG",

  UNAUTHORIZED = "UNAUTHORIZED",
  FORBIDDEN = "FORBIDDEN",
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",

  INVALID_TOKEN = "INVALID_TOKEN",
  INVALID_REFRESH_TOKEN = "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_REQUIRED = "REFRESH_TOKEN_REQUIRED",
  REFRESH_TOKEN_MISMATCH = "REFRESH_TOKEN_MISMATCH",

  VALIDATION_FAILED = "VALIDATION_FAILED",
  INVALID_REQUEST = "INVALID_REQUEST",

  NOT_FOUND = "NOT_FOUND",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  ARTICLE_NOT_FOUND = "ARTICLE_NOT_FOUND",
  NOTIFICATION_NOT_FOUND = "NOTIFICATION_NOT_FOUND",

  ALREADY_EXISTS = "ALREADY_EXISTS",
  USER_ALREADY_EXISTS = "USER_ALREADY_EXISTS",

  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",

  USER_CREATED_SUCCESSFULLY = "USER_CREATED_SUCCESSFULLY",
  LOGIN_SUCCESSFUL = "LOGIN_SUCCESSFUL",
  ACCESS_TOKEN_REFRESHED = "ACCESS_TOKEN_REFRESHED",

  ARTICLE_CREATED_SUCCESSFULLY = "ARTICLE_CREATED_SUCCESSFULLY",
  ARTICLES_FETCHED_SUCCESSFULLY = "ARTICLES_FETCHED_SUCCESSFULLY",
  ARTICLE_FETCHED_SUCCESSFULLY = "ARTICLE_FETCHED_SUCCESSFULLY",
  MY_ARTICLES_FETCHED_SUCCESSFULLY = "MY_ARTICLES_FETCHED_SUCCESSFULLY",
  ARTICLE_UPDATED_SUCCESSFULLY = "ARTICLE_UPDATED_SUCCESSFULLY",
  ARTICLE_DELETED_SUCCESSFULLY = "ARTICLE_DELETED_SUCCESSFULLY",
  ARTICLE_APPROVED_SUCCESSFULLY = "ARTICLE_APPROVED_SUCCESSFULLY",
  ARTICLE_REJECTED_SUCCESSFULLY = "ARTICLE_REJECTED_SUCCESSFULLY",

  NOTIFICATIONS_FETCHED_SUCCESSFULLY = "NOTIFICATIONS_FETCHED_SUCCESSFULLY",
  NOTIFICATION_MARKED_AS_READ = "NOTIFICATION_MARKED_AS_READ",

  PASSWORD_RESET_EMAIL_SENT_SUCCESSFULLY = "PASSWORD_RESET_EMAIL_SENT_SUCCESSFULLY",
  PASSWORD_RESET_SUCCESSFULLY = "PASSWORD_RESET_SUCCESSFULLY",
  INVALID_RESET_TOKEN = "INVALID_RESET_TOKEN",
  RESET_TOKEN_EXPIRED = "RESET_TOKEN_EXPIRED",

  REJECTION_REASON_REQUIRED = "REJECTION_REASON_REQUIRED",

  API_IS_RUNNING = "API_IS_RUNNING",
}
